set character_set_client=utf8;
set character_set_results=utf8;
set character_set_connection=utf8;
set character_set_server=utf8;
set character_set_database=utf8;

USE berryIP;
DROP TABLE IF EXISTS IP_INFO;
create table IP_INFO(\
	IP_ADDR VARCHAR(16) NOT NULL,\
	MAC_ADDR VARCHAR(18) NOT NULL,\
	OWNER VARCHAR(20) NOT NULL,\
	PERMISSION_DATE datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,\
	IS_OK CHAR(1) DEFAULT 0 NOT NULL,\
	IS_PROTECTED CHAR(1) DEFAULT 0 NOT NULL,\
	PRIMARY KEY(IP_ADDR)\
);

DROP TABLE IF EXISTS USER_INFO;
create table USER_INFO(\
	USER_ID VARCHAR(30) NOT NULL,\
	USER_PW VARCHAR(50) NOT NULL,\
	USER_NAME VARCHAR(20) NOT NULL,\
	USER_REMARK VARCHAR(100),\
	ATUHORITY CHAR(1) DEFAULT 0 NOT NULL,\
	LOGIN_FAIL_COUNT INT(4) DEFAULT 0 NOT NULL,\
	IS_LOCK CHAR(1) DEFAULT 0 NOT NULL,\
	LATEST_LOCK_DATE DATETIME,\
	PRIMARY KEY(USER_ID)\
);
